[package]
name = "model"
version = "0.1.0"
authors = ["kha"]
edition = "2018"

[dependencies]
rtdlib = { version = "1.7.0", features = [ "sys" ] }

[dependencies.mongodb]
version = "1.2.1"
default-features = false
features = ["sync"]
