FROM rust:1.48

# Install tdlib
RUN apt update
RUN apt upgrade -y
RUN apt install -y make git zlib1g-dev libssl-dev gperf php-cli cmake g++
RUN git clone https://github.com/tdlib/td.git
WORKDIR /td
RUN mkdir build
WORKDIR /td/build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
RUN cmake --build . --target install
RUN cp -r ../tdlib/* /usr